### ISSUE TITLE
`SIGINT` while waiting for login/register input causes full stack trace

### ISSUE THREAD

**Issue by mitchhentges** [tickbin/tickbin#133]
Ideally, if a user decides not to register/login anymore, they should be able to `CTRL-C`, and the application should quietly close.

However, `tickbin` wants to inform me about the entire story of _how_ it dies a terrible death, which, as a user, I'm not too concerned about:

```
$ tick register
username readline.js:925
            throw err;
            ^

Error: canceled
    at Interface.<anonymous> (/home/mitch/dev/tickbin/node_modules/read/lib/read.js:66:13)
    at emitNone (events.js:80:13)
    at Interface.emit (events.js:179:7)
    at Interface._ttyWrite (readline.js:691:16)
    at ReadStream.onkeypress (readline.js:106:10)
    at emitTwo (events.js:100:13)
    at ReadStream.emit (events.js:185:7)
    at emitKeys (readline.js:1251:14)
    at next (native)
    at ReadStream.onData (readline.js:919:36)

**Comment by jonotron** [comment]
This seems a reasonably simple change to make and would be good considering we currently use a betakey for registration, so the registration process is not entirely useful just yet.
