### ISSUE TITLE
Specify that we require Node 4 more clearly in the README

### ISSUE THREAD

**Issue by chrisfosterelli** [tickbin/tickbin#141]
Right after installing with the instructions in the README, the following occurs:

```bash
➜  tickbin-server git:(change-prefix) ✗ tick
/usr/local/lib/node_modules/tickbin/build/commands/tick-log.js:30
  let argv = yargs.usage('Usage: tick log [options] [message]').example('tick 
  ^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/tickbin/build/tick.js:12:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

We mention that Node 4 is required in the developer section, but we should probably make this more clear to people who are also installing the application.

**Comment by chrisfosterelli** [comment]
We should also consider using `engineStrict : true` in our `package.json`, this would block people from installing it at all unless they are on Node 4.

We could potentially do this in addition or instead of the documentation update. Thoughts?

**Comment by chadfawcett** [comment]
I think adding `engineStrict: true` would be a good idea. At least until we decide if we want to implemtn #142

**Comment by chrisfosterelli** [comment]
Ugh so it looks like [they are removing](http://blog.npmjs.org/post/110924823920/npm-weekly-5) engineStrict... The README warning will have to do!
